services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NOTION_SECRET=${NOTION_SECRET:-}
      - NOTION_DB=${NOTION_DB:-}
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL:-}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN:-}
    restart: unless-stopped
