import PageShell from "@/components/page-shell";
import LegalSections, { L, type LegalSection } from "@/components/legal-sections";
import { CONTACT, ENTITY, JURISDICTION, LAST_UPDATED } from "@/lib/legal";

export const metadata = {
  title: "Privacy Policy",
  description:
    "What BeFit AI collects, why, where it is stored, who it is shared with, and how to delete all of it.",
};

/*
  This has to agree with two other things or it becomes a liability rather than
  a protection: the App Privacy questionnaire in App Store Connect, and the
  in-app policy in lib/ui/features/profile/views/legal_document_page.dart.
  Change one, change all three.

  The collection list below is written from what the app actually does — the
  onboarding fields, the three camera surfaces, the error log table — not from
  a generic template.
*/
const SECTIONS: LegalSection[] = [
  {
    heading: "Who handles your data",
    body: [
      `BeFit AI is provided by ${ENTITY}, who decides how and why your personal data is processed and is responsible for it.`,
      <>
        For anything in this policy, including a request to see or delete your
        data, write to <L href={`mailto:${CONTACT}`}>{CONTACT}</L>.
      </>,
    ],
  },
  {
    heading: "What we collect",
    body: [
      "Account details. Your name and email address. If you use Sign in with Apple and choose to hide your address, we receive a relay address instead of your real one — see section 5.",
      "What you tell us during onboarding. Your goal, training experience, how many days a week you can train, the equipment you can reach, your height, weight, gender and date of birth.",
      "What you log. Workouts, exercises, sets, reps, weights, session durations, streaks, notes and any feedback you give on a session.",
      "Photos you choose to take. Meal photos for calorie and macro estimates, physique photos for body-composition analysis, equipment photos for the gym scanner, and progress photos. Progress photos are stored on your device and are not uploaded.",
      "Technical data. Device and app version, and error reports when something fails — these include the type of error and where it happened, so we can fix it.",
    ],
  },
  {
    heading: "Why we collect it",
    body: [
      "To build and rebuild your training plan around what you have actually done, to answer your questions in the coach chat with your real history in view, to estimate what is on your plate, to show your progress over time, and to send the motivational messages you have asked for in the tone you chose.",
      "To run the subscription: your entitlement is checked so paid features unlock for you and not for someone else.",
      "To keep the app working. Error reports tell us what is broken. We do not use any of this for advertising, and we do not build a profile of you for anyone else's purposes.",
    ],
  },
  {
    heading: "AI processing",
    body: [
      "Your plans, coaching replies and analysis are generated by AI models run by our providers. To produce them, the relevant parts of your data — your profile, your recent sessions, the photo you just took — are sent to those providers for processing.",
      "Your data is not used to train publicly available models. Providers act on our instructions under contract and cannot use your content for their own purposes.",
    ],
  },
  {
    heading: "Sign in with Apple and private relay",
    body: [
      "If you sign in with Apple you can choose to hide your email address. Apple then gives us a relay address that forwards to you, and we never see your real one. Everything in the app works normally with a relay address.",
      "Apple sends us your name only on the very first sign-in, and only if you allow it. If you decline, your profile simply has no name until you set one.",
    ],
  },
  {
    heading: "Where your data is stored",
    body: [
      "Account and training data is held in our Supabase-hosted Postgres database, protected by row-level security so that a signed-in user can reach their own rows and no one else's.",
      "Our backend runs on Google Cloud Run in the United States, which is where AI generation happens. If you are in the UK or the EEA, that means your data is transferred outside your region; those transfers rely on standard contractual clauses.",
      "Some data is also cached on your device so the app works offline — your saved plans, your preferences, your chat history and your progress photos.",
    ],
  },
  {
    heading: "Who we share it with",
    body: [
      "Only the providers needed to run the service: our database and hosting providers, the AI providers described in section 4, Apple for payments and subscription status, and RevenueCat, which tells us whether your subscription is active.",
      "Each acts as our processor under a data-processing agreement. We may also disclose data where the law requires it.",
    ],
  },
  {
    heading: "What we never do",
    body: [
      "We do not sell your personal data. We do not share it with advertisers or data brokers. We do not track you across other apps or websites, and we do not use your training history or your photos for anything other than running BeFit AI for you.",
    ],
  },
  {
    heading: "How long we keep it",
    body: [
      "Your account data is kept while your account exists. Delete your account from Profile, then Delete Account, and your profile, training history, chat history and uploaded photos are removed with it. Progress photos held on your device go when you delete the app.",
      "Deletion cannot be undone. Backups are overwritten on a rolling basis and clear within 30 days. We may keep a minimal record of a transaction where tax or accounting law requires it.",
      <>
        If you cannot get into the app to delete your account, email{" "}
        <L href={`mailto:${CONTACT}`}>{CONTACT}</L> and we will do it for you.
      </>,
    ],
  },
  {
    heading: "Your rights",
    body: [
      "You can ask for a copy of your data, ask us to correct it, ask us to delete it, ask us to restrict how we use it, object to a particular use, or ask for it in a portable format. Where we rely on your consent — for photo analysis, for example — you can withdraw it at any time by not using that feature.",
      <>
        Write to <L href={`mailto:${CONTACT}`}>{CONTACT}</L> and we will respond
        within 30 days. If you think we have handled your data badly, you can
        also complain to the data protection authority where you live; in{" "}
        {JURISDICTION} that is the Information Commissioner&rsquo;s Office.
      </>,
    ],
  },
  {
    heading: "Children",
    body: [
      "BeFit AI is not intended for anyone under 16 and we do not knowingly collect their data. If you believe a child has created an account, tell us and we will remove it.",
    ],
  },
  {
    heading: "Security",
    body: [
      "Data is encrypted in transit. Database access is scoped per user by row-level security, and our own access to production data is limited to what is needed to run and support the service.",
      "No system is perfectly secure. If a breach affects your data, we will tell you and the relevant authority as the law requires.",
    ],
  },
  {
    heading: "Changes to this policy",
    body: [
      "We will update this page when what we collect or how we use it changes. The date at the top always reflects the current version, and we will tell you in the app before any material change takes effect.",
    ],
  },
  {
    heading: "Contact",
    body: [
      <>
        Questions about your data, or a request to exercise any of the rights
        above: <L href={`mailto:${CONTACT}`}>{CONTACT}</L>.
      </>,
    ],
  },
];

export default function PrivacyPage() {
  return (
    <PageShell
      eyebrow="Legal"
      title="Privacy Policy"
      intro="What BeFit AI collects, why it needs it, where it goes, and how to get rid of all of it. No part of it is sold, and none of it is used to advertise to you."
      updated={LAST_UPDATED}
    >
      <LegalSections sections={SECTIONS} />

      <p className="mt-8 text-sm leading-relaxed text-bone-dim">
        See also our <L href="/terms">Terms of Use</L> and{" "}
        <L href="/support">Support</L> pages.
      </p>
    </PageShell>
  );
}
